export type Tier = { min: number; max: number | null; price: string };
export type Product = {
  sku: string;
  name: string;
  brand: string;
  mpn: string;
  price: string | null;
  purchasable: boolean;
  hasDatasheet: boolean;
  tiers: Tier[];
  images: string[];
  description: string;
  summary: string;
  categories: string[];
  stock: number | null;
  backorder: boolean;
  specs: string[][];
  sale: boolean;
  new: boolean;
  source: string;
  documents: string[];
  arrivalRank: number;
};
export type DocumentRecord = {
  id: string;
  title: string;
  filename: string;
  format: string;
  classification: string;
  bytes: number;
  url: string;
  source: string;
  skus: string[];
  brands: string[];
  categories: string[];
};
export type CartLine = { sku: string; quantity: number };
export type Filters = {
  q: string;
  category: string;
  brands: string[];
  availability: string[];
  prices: string[];
  data: string[];
  min: string;
  max: string;
  collection: string;
  industry: string;
  sort: string;
  view: string;
  page: number;
  perPage: number;
};
